spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      routes:
        - id: users_route			  # 指定路由唯一标识
          uri: lb://users             # 指定路由服务的地址
          predicates:
            - Path=/user/**			  # 指定路由规则

        - id: emps_route
          uri: lb://emps
          predicates:
            - Path=/emp/**
      # 解决前后端跨域问题，前端端口为8080，后端端口为8992，这时候需要配置下面所示
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
        add-to-simple-url-handler-mapping: true

server:
  port: 8992